// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function Greet(arg1:string):Promise<string>;

export function Open():Promise<main.FileData>;

export function OpenFolder(arg1:string):Promise<void>;

export function Save(arg1:string,arg2:string):Promise<string>;

export function SaveAs(arg1:string):Promise<string>;
