// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Open() {
  return window['go']['main']['App']['Open']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function Save(arg1, arg2) {
  return window['go']['main']['App']['Save'](arg1, arg2);
}

export function SaveAs(arg1) {
  return window['go']['main']['App']['SaveAs'](arg1);
}
